plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 31
    buildToolsVersion "32.0.0"



    android.applicationVariants.all { variant ->
        if (variant.getName() == "release") {
            buildConfigField "boolean", "IS_RELEASE", "true"
            variant.mergedFlavor.manifestPlaceholders = [appName: "AyMusic"]
        } else {
            buildConfigField "boolean", "IS_RELEASE", "false"
            variant.mergedFlavor.applicationId = "com.aketsuky.aymusic.debug"
            variant.mergedFlavor.manifestPlaceholders = [appName: "AyMusic Dev"]
        }
        variant.mergeAssetsProvider.configure  {
            doLast {
                delete(fileTree(dir: outputDir, includes: ['node_modules/', '.git/**']))
            }
        }
    }

    defaultConfig {
        applicationId "com.aketsuky.aymusic"
        minSdkVersion 24
        targetSdkVersion 31
        versionCode 6
        versionName "0.2.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.6.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.4.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}